//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S6Patcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S6Patcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EMXBinData {
            get {
                object obj = ResourceManager.GetObject("EMXBinData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Erstellen der Backup-Datei! Abbrechen ...
        ///Error when creating backup file! Aborting ....
        /// </summary>
        internal static string ErrorBackup {
            get {
                return ResourceManager.GetString("ErrorBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup konnte nicht wiederhergestellt werden!
        ///Backup could not be restored!.
        /// </summary>
        internal static string ErrorBackupFail {
            get {
                return ResourceManager.GetString("ErrorBackupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua-Fixes: Datei konnte nicht geschrieben werden!
        ///Lua-Fixes: File could not be written!.
        /// </summary>
        internal static string ErrorLuaScriptFixes {
            get {
                return ResourceManager.GetString("ErrorLuaScriptFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Datei ausgewählt oder Datei existiert nicht!
        ///No file chosen or file does not exist!.
        /// </summary>
        internal static string ErrorNoFile {
            get {
                return ResourceManager.GetString("ErrorNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Ausführungsdatei gewählt! Abbrechen ...
        ///Invalid executable has been choosen! Aborting ....
        /// </summary>
        internal static string ErrorWrongVersion {
            get {
                return ResourceManager.GetString("ErrorWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup wurde erfolgreich wiederhergestellt!
        ///Backup has been successfully restored!.
        /// </summary>
        internal static string FinishedBackup {
            get {
                return ResourceManager.GetString("FinishedBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgang Erfolgreich!
        ///Finished successfully!.
        /// </summary>
        internal static string FinishedSuccess {
            get {
                return ResourceManager.GetString("FinishedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MainMenuUserScript {
            get {
                object obj = ResourceManager.GetObject("MainMenuUserScript", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UserScriptLocal {
            get {
                object obj = ResourceManager.GetObject("UserScriptLocal", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
