//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S6Patcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S6Patcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.com/invite/7SGkQtAAET.
        /// </summary>
        internal static string DiscordMainLink {
            get {
                return ResourceManager.GetString("DiscordMainLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EMXBinData {
            get {
                object obj = ResourceManager.GetObject("EMXBinData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create backup file! Aborting ....
        /// </summary>
        internal static string ErrorBackup {
            get {
                return ResourceManager.GetString("ErrorBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restore backup! Aborting ....
        /// </summary>
        internal static string ErrorBackupFail {
            get {
                return ResourceManager.GetString("ErrorBackupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching is currently in progress.
        ///Do you want to exit?.
        /// </summary>
        internal static string ErrorClosingWhenPatching {
            get {
                return ResourceManager.GetString("ErrorClosingWhenPatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid executable has been choosen! Aborting ....
        /// </summary>
        internal static string ErrorInvalidExecutable {
            get {
                return ResourceManager.GetString("ErrorInvalidExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam executable invalid, has to be unpacked with the tool &quot;Steamless&quot; before using the S6Patcher!.
        /// </summary>
        internal static string ErrorInvalidExecutableSteam {
            get {
                return ResourceManager.GetString("ErrorInvalidExecutableSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua-Fixes: File could not be written!.
        /// </summary>
        internal static string ErrorLuaScriptFixes {
            get {
                return ResourceManager.GetString("ErrorLuaScriptFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen or file does not exist!.
        /// </summary>
        internal static string ErrorNoFile {
            get {
                return ResourceManager.GetString("ErrorNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Eisenmonoxid/S6Patcher/blob/master/Features/Features.md.
        /// </summary>
        internal static string FeaturesLink {
            get {
                return ResourceManager.GetString("FeaturesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup has been successfully restored!.
        /// </summary>
        internal static string FinishedBackup {
            get {
                return ResourceManager.GetString("FinishedBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished successfully!.
        /// </summary>
        internal static string FinishedSuccess {
            get {
                return ResourceManager.GetString("FinishedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Eisenmonoxid/S6Patcher.
        /// </summary>
        internal static string GithubMainLink {
            get {
                return ResourceManager.GetString("GithubMainLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MainMenuUserScript_Raw {
            get {
                object obj = ResourceManager.GetObject("MainMenuUserScript_Raw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mod {
            get {
                object obj = ResourceManager.GetObject("mod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %x KB will be downloaded from the GitHub repository.
        ///Continue?.
        /// </summary>
        internal static string ModDownloadMessage {
            get {
                return ResourceManager.GetString("ModDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Eisenmonoxid/S6Patcher/raw/refs/heads/master/Source/Resources/Gamefiles/Modfiles.zip.
        /// </summary>
        internal static string ModLink {
            get {
                return ResourceManager.GetString("ModLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the path to the &quot;Options.ini&quot; configuration file that the game has created!.
        /// </summary>
        internal static string MonoOptionsFile {
            get {
                return ResourceManager.GetString("MonoOptionsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UserScriptGlobal {
            get {
                object obj = ResourceManager.GetObject("UserScriptGlobal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UserScriptLocal {
            get {
                object obj = ResourceManager.GetObject("UserScriptLocal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/Eisenmonoxid/S6Patcher/refs/heads/master/Version.txt.
        /// </summary>
        internal static string VersionFileLink {
            get {
                return ResourceManager.GetString("VersionFileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select recommended settings or customize manually?.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
